const SDresourceList = [
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Aberdeen Salvation Army",
    distributionSchedule: "Contact Agency for Distribution Times",
    buildingLocation: "",
    address: "1003 6th Ave SW",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "605-225-7410",
    url: "",
    notes: "Food Pantry: week’s supply of food, can use every 90 days. Free community meal Monday to Friday 12:00pm to 1:00 pm",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Bowdle Food Pantry",
    distributionSchedule: "Monday - Thursday 10:00am to 4:00pm (closed over lunch) or by appointment (call Joell Bieber at 605-281-0828 for scheduling)",
    buildingLocation: "City office",
    address: "4093 9th Ave",
    city: "Bowdle",
    state: "SD",
    zip: "57428",
    phone: "605-281-0828",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Brown Bag Food Pantry of Faulkton",
    distributionSchedule: "4th Tues of the month 12-2 and 5:30-7; can call Karen Collins at 605-350-4227 for immediate needs",
    buildingLocation: "United Church of Faulkton (Methodist Church)",
    address: "1011 St John St",
    city: "Faulkton",
    state: "SD",
    zip: "57438",
    phone: "605-598-6580 (Church), 605-350-4227 (Karen Collins)",
    url: "https://www.facebook.com/FaulktonUMC/",
    notes: "No application process or requirements. All people are welcome. All donations are welcome, food and non-food. Can accept perishables. Each person receives one brown bag with about 17 items. Items are meant to combine to make 2-3 meals. Typically includes1 lb fresh ground beef, canned chicken and/or tuna (with hamburger/chicken/tuna helper meal boxes), 3 cans of vegetables, 3 cans of fruit, and soup. Occasstional extras: cake mix, pancake mix & syrup, honey, powdered milk, pasta sauce, noodles, potato flakes, etc. Try to offer atleast one drink, such as coffee, tea or lemonade mix. No diapers or wipes available right now, but will gladly accept as donations.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "St Thomas Food Pantry",
    distributionSchedule: "Tues, Wed, & Thurs 10am-3pm",
    buildingLocation: "St. Thomas Catholic Church",
    address: "1013 Court St",
    city: "Faulkton",
    state: "SD",
    zip: "57438",
    phone: "605-598-6590",
    url: "",
    notes: "No application process or requirements. All people are welcome. Accepting cash and non-perishable food donations. The church collects food and takes to the food pantry in Redfield. The Redfield food pantry then sends back bags of groceries that can be given out. Some non-food items available, but not consistenly.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Groton Food Pantry",
    distributionSchedule: "Contact Agency for Distribution Times",
    buildingLocation: "",
    address: "109 North 3rd Street",
    city: "Groton",
    state: "SD",
    zip: "57445",
    phone: "605-397-7097",
    url: "",
    notes: "Left a VM for a call back (ah)",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Lemmon Food Pantry",
    distributionSchedule: "Friday 7:00pm-9:00pm; Or by appointment",
    buildingLocation: "",
    address: "211 1st Avenue West",
    city: "Lemmon",
    state: "SD",
    zip: "57638",
    phone: "605-374-7617",
    url: "",
    notes: "Left a VM for a call back (ah)",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Wessington Springs Food Pantry",
    distributionSchedule: "Distributions on the Third Tuesday of the month, 10am to 11am",
    buildingLocation: "",
    address: "608 1st St NE",
    city: "Wessington Springs",
    state: "SD",
    zip: "57382",
    phone: "605-999-5883",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Scoreboard Bar and Grill",
    distributionSchedule: "will have a donation jar that will run from now until november 7th",
    buildingLocation: "",
    address: "56 3rd ST SE",
    city: "Huron",
    state: "SD",
    zip: "57350",
    phone: "605-352-7580",
    url: "",
    notes: "Jeremy informed me he is in partnership with Medi's Juice Box (previously known as Healthy Fix) and that scoreboard will match all monetary donations received at Medi's Juice Box up to $500. Donations will go towards Salvation Army-Huron",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Medi's Juice Box (Health Fix)",
    distributionSchedule: "will have a donation jar that will run from now until november 7th",
    buildingLocation: "",
    address: "1502 Dakota Ave S",
    city: "Huron",
    state: "SD",
    zip: "57350",
    phone: "",
    url: "",
    notes: "Per my conversation with Jeremy from Scoreboard this business is also having a food drive (non-perishables) and accepting other items as diapers, formula and basic hygiene items that will be donated to Salvation Army in Huron.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Salvation Army",
    distributionSchedule: "",
    buildingLocation: "",
    address: "237 Illinois Ave SW",
    city: "Huron",
    state: "SD",
    zip: "57350",
    phone: "605-352-3438",
    url: "",
    notes: "Salvation Army Huron made a Facebook publication that if the current situation doesn't change they will open a daily soup kitchen at 6pm and offer a simple breakfast (for children only) that consists of a snack item and fruit to take home for the morning. No changes are made to their daily M-F Lunch program.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Helping Hands",
    distributionSchedule: "Open Tuesday, Thursday and Saturday 12:00 pm to 4:00 pm",
    buildingLocation: "",
    address: "403 Dakota Ave NE",
    city: "Huron",
    state: "SD",
    zip: "57350",
    phone: "619-665-2636",
    url: "",
    notes: "There is an application process to receive a food box containing perishable, non-perishable, and hygiene items (if available). Applicants must present an ID with their current address. If the ID does not have a current address a bill/mail with their name and current address is accepted. Citizenship is not required-any valid ID and proof of address will suffice. Without documentation, individuals may receive up to three items. Donations of goods and money are welcome. Formula, baby food, and diapers are not typically distributed but they are accepted as donations. Boxes are available once every 30 days. Cut off time for food boxes is at 3:50pm",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Taco Johns- Huron",
    distributionSchedule: "Only this Friday Oct 31 through November 2nd, 2025",
    buildingLocation: "",
    address: "410 Dakota Ave N",
    city: "Huron",
    state: "SD",
    zip: "57350",
    phone: "605-352-4474",
    url: "",
    notes: "Taco Johns will be offering a free meal to anyone who needs it. Ask at the store for the \"community Special\". They will be offering a bean or beef burrito along with an order of Potato Oles for anyone in need. No questions asked.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Horizon Health",
    distributionSchedule: "formula, Diapers and wipes (as available) and basic needs for pregnant woman.",
    buildingLocation: "",
    address: "1000 18th ST SW, Suite 27",
    city: "Huron",
    state: "SD",
    zip: "57350",
    phone: "605-554-1015",
    url: "",
    notes: "Has to have established care with Horizon Health. Does accept basic hygiene items and baby essentials as donations.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "1st Stop Insurance",
    distributionSchedule: "Is having a Food Drive from Nov 3rd- Nov 7th, 2025.",
    buildingLocation: "",
    address: "1507 Dakota Ave S",
    city: "Huron",
    state: "SD",
    zip: "57350",
    phone: "605-352-5719",
    url: "",
    notes: "(only non perishables) and monetary donations- will be donated to the Salvation Army of Huron and Huron Helping Hands. (basic pantry items and hygiene items). **for every box of cereal donated 1st stop/ Juffer Inc will match up to 500 boxes.**",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Feeding South Dakota",
    distributionSchedule: "Every 3rd Thursday of the month.",
    buildingLocation: "",
    address: "120 Wyoming Ave SW",
    city: "Huron",
    state: "SD",
    zip: "57350",
    phone: "",
    url: "",
    notes: "requirements: state ID or drivers licence. Once a month",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Tri County Good Samaritan Center",
    distributionSchedule: "Open Tuesday 4:00pm to 7:00pm and Thursday 10:00am to 5:00pm",
    buildingLocation: "",
    address: "19 E 7th Ave",
    city: "Redfield",
    state: "SD",
    zip: "57469",
    phone: "605-472-3314",
    url: "",
    notes: "Providing a food pantry and thrift store to the counties of Spink, Hand, and Faulk.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Sacred Heart Church",
    distributionSchedule: "Tuesday and Thursday 11:00am to 1:30 pm",
    buildingLocation: "",
    address: "503 2nd Ave SE",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "605-225-7065",
    url: "sacredheartaberdeen@gmail.com",
    notes: "Provides food, diapers, and school supplies to individuals in need of assistance.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "St Mary's Church",
    distributionSchedule: "Tuesday 10:30am to 12:30pm   Wednesday 12:30pm to 2:30pm",
    buildingLocation: "",
    address: "409 2nd Ave NE",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "605-229-4422",
    url: "",
    notes: "Provides food, diapers, and school supplies to individuals in need of assistance.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Pierre/Ft. Pierre Food Pantry",
    distributionSchedule: "Pantry is by appointment only. Monday, Tuesday, Wednesday, & Friday open 4:00pm-5:30pm, Thursday open 4:00pm-5:00pm",
    buildingLocation: "",
    address: "S. Ree St.",
    city: "Pierre",
    state: "SD",
    zip: "57501",
    phone: "605-224-8731",
    url: "",
    notes: "3 pantry's a year for food. Will ask questions about income. 1st come 1st serve depending on family size. Takes donations.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Wellness Pantry at Avera Pierre Clinic",
    distributionSchedule: "",
    buildingLocation: "",
    address: "801 E. Sioux Ave",
    city: "Pierre",
    state: "SD",
    zip: "57501",
    phone: "",
    url: "",
    notes: "Food pantry to provide food to patients in need. Will be screened for food insecurity during their appointment. Those who screen positive will receive a bag of food from the pantry during their visit. Bags will offer a 3-5 day emergency food supply.",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Aberdeen Feeding SD Mobile",
    distributionSchedule: "Nov 25 11:00-1:00pm CT, Dec 23 11:00-1:00pm CT",
    buildingLocation: "Freedom Church",
    address: "516 Production St",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "Available monthly. Must have a SD address to visit one Feeding SD Mobile Food Distribution each month.",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Bison Feeding SD Mobile",
    distributionSchedule: "Nov 20 1:30-2:30pm MT, Dec 18 1:30-2:30pm MT",
    buildingLocation: "Bison School",
    address: "200 E Carr St",
    city: "Bison",
    state: "SD",
    zip: "57620",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Faith Feeding SD Mobile",
    distributionSchedule: "Nov 20 10:00-11:00am MT, Dec 18 10:00-11:00am MT",
    buildingLocation: "Faith Legion Hall",
    address: "102 3rd St",
    city: "Faith",
    state: "SD",
    zip: "57626",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Faulkton Feeding SD Mobile",
    distributionSchedule: "Nov 10 1:30-2:30pm CT, Dec 8 1:30-2:30pm CT",
    buildingLocation: "Faulkton Fire House",
    address: "200 8th Ave",
    city: "Faulkton",
    state: "SD",
    zip: "57438",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Herreid Feeding SD Mobile",
    distributionSchedule: "Nov 4 10:00-11:00am CT, Dec 2 10:00am-11:00am CT",
    buildingLocation: "Campbell County Community Center",
    address: "107 Main St N",
    city: "Herreid",
    state: "SD",
    zip: "57632",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Ipswich Feeding SD Mobile",
    distributionSchedule: "Nov 11 10:30am-11:30am CT, Dec 9 10:30-11:30am CT",
    buildingLocation: "Ipswich 4-H Building",
    address: "515 7th St",
    city: "Ipswich",
    state: "SD",
    zip: "57457",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Leola Feeding SD Mobile",
    distributionSchedule: "Nov 11 12:30-1:30pm CT, Dec 9 12:30-1:30pm CT",
    buildingLocation: "Catholic Parish Center",
    address: "1006 Main St",
    city: "Leola",
    state: "SD",
    zip: "57456",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "SWO Food Pantry",
    distributionSchedule: "Monday 1:00 PM-4:00 PM, Wednesday-Friday 9 AM-12:00 PM and 1:00 PM-3:00 PM",
    buildingLocation: "",
    address: "45672 Veterans Memorial Dr",
    city: "Agency Village",
    state: "SD",
    zip: "57262",
    phone: "605-698-3643",
    url: "",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Grant County Food Pantry",
    distributionSchedule: "Hours Monday-Friday 8 am-4:30 pm  Call to schedule an appointment.",
    buildingLocation: "County Courthouse",
    address: "210 E. 5th Avenue",
    city: "Milbank",
    state: "SD",
    zip: "57252",
    phone: "605-432-6571",
    url: "",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Brookings County Food Pantry",
    distributionSchedule: "M, W, F; 1:00pm-4:30p",
    buildingLocation: "",
    address: "908 Hope Drive",
    city: "Brookings",
    state: "SD",
    zip: "57006",
    phone: "605-692-5007",
    url: "https://www.feedingbrookings.org/",
    notes: "have a picture ID and current mail with current address. Brookings County residents only.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Feeding Brookings - Ascension Lutheran Church",
    distributionSchedule: "Food distribution weekly on Thursdays - 3pm-5pm",
    buildingLocation: "",
    address: "2030 3rd St",
    city: "Brookings",
    state: "SD",
    zip: "57006",
    phone: "605-697-0477",
    url: "feedingbrookings@brookings.net",
    notes: "Show up and get in line of cars. Some paperwork and low income requirements.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Miner County (Howard) Food Pantry",
    distributionSchedule: "Tuesday and Thursday, 8:30 AM-4:00 PM",
    buildingLocation: "",
    address: "108 E Highway 34",
    city: "Howard",
    state: "SD",
    zip: "57349",
    phone: "605-772-5712",
    url: "https://www.interlakescap.com/custom/miner-county",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Sisseton Food Pantry",
    distributionSchedule: "call for distribution dates, 3:00 PM-5:00 PM",
    buildingLocation: "Family Life Church",
    address: "405 1st Ave W",
    city: "Sisseton",
    state: "SD",
    zip: "57262",
    phone: "605-698-7631",
    url: "",
    notes: "do not need to qualify",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Horizons Thrift Store (Wilmot)",
    distributionSchedule: "Wednesday-Friday, 1:00 PM-5:00 PM and Saturday 10:00 AM-2:00 PM",
    buildingLocation: "",
    address: "710 Main St",
    city: "Wilmot",
    state: "SD",
    zip: "57279",
    phone: "",
    url: "",
    notes: "***Could not verify with phone as no phone number or website. according to facebook it's a non profit thrift store.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Storehouse Program at Access Ministry",
    distributionSchedule: "Supply of food items",
    buildingLocation: "",
    address: "25 W Kemp Ave",
    city: "Watertown",
    state: "SD",
    zip: "57201",
    phone: "605-878-1478",
    url: "",
    notes: "Left a VM for a call back",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Blessing Box Program at Trinity Episcopal Church",
    distributionSchedule: "Not a food pantry, rather a cupboard to offer needed items to help people get by",
    buildingLocation: "",
    address: "612 3rd St NE",
    city: "Watertown",
    state: "SD",
    zip: "57201",
    phone: "605-868-2425",
    url: "",
    notes: "Left a VM for a call back",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Salvation Army Watertown",
    distributionSchedule: "Assists individuals and families with a food pantry and food box. Food boxes are available for pickup once a month. A community meal is served M/W/F from 11:30am-12:30pm.",
    buildingLocation: "",
    address: "621 4th St SE",
    city: "Watertown",
    state: "SD",
    zip: "57201",
    phone: "605-886-4030",
    url: "",
    notes: "You can dine-in or get a to-go box. Provide diapers, baby food, formula and soft food.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Food Distribution Program at Sisseton-Wahpeton Oyate Tribe",
    distributionSchedule: "Food distribution provides food packages to low-income families in Marshall, Day and Roberts counties, Tribal members in surrounding counties including Codington County.",
    buildingLocation: "East of the Tribal Headquarters",
    address: "",
    city: "Sisseton",
    state: "SD",
    zip: "57262",
    phone: "605-698-3762",
    url: "",
    notes: "Must qualify and bring in all required information. Call for distribution dates. Hours of distribution 9-11:30am and 1-3pm.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Hot Meal Program at Harvest Table",
    distributionSchedule: "Home cooked meal served every Monday at 5:30pm.",
    buildingLocation: "Brookings First United Methodist Church",
    address: "625 5th St",
    city: "Brookings",
    state: "SD",
    zip: "57006",
    phone: "605-692-4345",
    url: "",
    notes: "Diapers, baby wipes, household items and personal care items available. No cost",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Bethania Lutheran Food Pantry",
    distributionSchedule: "Primarily food to those in need. Some basic needs available.",
    buildingLocation: "",
    address: "9 1st St",
    city: "Rosholt",
    state: "SD",
    zip: "57260",
    phone: "605-537-4263",
    url: "",
    notes: "No qualification requirements",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Kingsbury County Food Pantry",
    distributionSchedule: "Open Tuesdays 1pm-4pm.",
    buildingLocation: "",
    address: "221 Calumet Ave SW",
    city: "DeSmet",
    state: "SD",
    zip: "57231",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Breadbasket Food Pantry",
    distributionSchedule: "1:30-5pm Thursdays",
    buildingLocation: "",
    address: "202 E 2nd Ave",
    city: "Flandreau",
    state: "SD",
    zip: "57028",
    phone: "605-573-0935",
    url: "",
    notes: "Serves Moody County, open to all who meet income guidelines. No one in crisis will be turned away. Occasionally offers household cleaning supplies and hygiene products.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "24/7 Community Food Pantry",
    distributionSchedule: "24 hour food pantry",
    buildingLocation: "Entryway to City Hall",
    address: "112 N Main Ave",
    city: "Colman",
    state: "SD",
    zip: "57017",
    phone: "605-534-3611",
    url: "",
    notes: "Non-perishable food items",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Douglas County (Armour) Food Pantry",
    distributionSchedule: "Food Pantry: Tuesday 12:00pm-4:00pm",
    buildingLocation: "",
    address: "706 Braddock St",
    city: "Armour",
    state: "SD",
    zip: "57317",
    phone: "605-999-0483",
    url: "",
    notes: "Income Guidelines apply, short application process that can be completed there in person. They do have limited formula on hand due to a recent donation that came in but normally does not have it on hand. Barb stated that the clients that they are currently serving are elderly members of the community. Barb stated that she is always excepting donations and has space for both perishables and none perishables. The site is set up as a shop your own food setting, Barb stated that they do limit items to family size",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Beresford Community Food Cupboard and Services",
    distributionSchedule: "Mon-Fri 1PM-6PM and Sat 9AM-1PM",
    buildingLocation: "",
    address: "106 N 3rd St",
    city: "Beresford",
    state: "SD",
    zip: "57004",
    phone: "605-763-8888",
    url: "",
    notes: "left VM for call back (AML)",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Beresford Faith in Action",
    distributionSchedule: "Open Thursday from 1-6P and every other Saturday from 9-1P. MUST MAKE APPT.",
    buildingLocation: "",
    address: "101 S 5th St",
    city: "Beresford",
    state: "SD",
    zip: "57004",
    phone: "605-763-8019",
    url: "",
    notes: "Beresford Faith in Action serves clients in need of food; utility and rent assistance in the city of Beresford as well as those living in Union or Lincoln County. Left VM for call back(AML)",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Centerville Food Pantry",
    distributionSchedule: "Wednesday 5:30 PM-6:30 PM",
    buildingLocation: "",
    address: "548 Broadway",
    city: "Centerville",
    state: "SD",
    zip: "57014",
    phone: "605-677-9609",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Elk Point Food Pantry",
    distributionSchedule: "Tuesday and Thursday, 10:00 AM-12:00 PM and 4:00 PM-6:00 PM",
    buildingLocation: "",
    address: "107 N Douglas St",
    city: "Elk Point",
    state: "SD",
    zip: "57025",
    phone: "605-212-5403",
    url: "https://www.facebook.com/p/Elk-Point-Food-Pantry-100064583026135/",
    notes: "Income based; provides commodity foods; food pantry; charity fund available. Covers southern Union County.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Fort Thompson Food Pantry",
    distributionSchedule: "The last 3 days of the month 1:00pm-4:00pm",
    buildingLocation: "",
    address: "817 SD Hwy 47",
    city: "Fort Thompson",
    state: "SD",
    zip: "57339",
    phone: "605-245-2350",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Diamond Willow Ministries Food Pantry",
    distributionSchedule: "Provides emergency food services on the reservation",
    buildingLocation: "",
    address: "22850 North Shore Rd",
    city: "Fort Thompson",
    state: "SD",
    zip: "57339",
    phone: "605-245-2685",
    url: "https://www.d-w-m.org/iocc-programming.html",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Bethany Mennonite Church Food Pantry",
    distributionSchedule: "1st and 3rd Friday of each month, 1:00 PM-5:00 PM",
    buildingLocation: "",
    address: "509 S Juniper St",
    city: "Freeman",
    state: "SD",
    zip: "57029",
    phone: "605-925-7311",
    url: "https://www.bethanymennonite.com/foodpantry",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Irene Food Pantry",
    distributionSchedule: "Wednesday 5:30 - 6:30",
    buildingLocation: "",
    address: "110 S Till",
    city: "Irene",
    state: "SD",
    zip: "57037",
    phone: "605-660-6558",
    url: "",
    notes: "Accepting donations, fill out short application but is usually same folks. Donations: non perishable usually. Gets some form Feeding SD and they fill in as needed. She does take perishables. Not usually having formula or diapers. On occasion will have formula donations. Accepts cash or food. Call you for any donations. Asks church and bank for donations for food drive. Only open Wed but she is available to meet someone on other days and pastor may have access on other days.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Kimball Food Pantry",
    distributionSchedule: "Thursday 5:00-6:30 pm",
    buildingLocation: "",
    address: "123 S Main St",
    city: "Kimball",
    state: "SD",
    zip: "57355",
    phone: "605-450-0740",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Lower Brule Food Pantry",
    distributionSchedule: "Sunday 1:00pm-4:00pm, Tuesdays & Thursdays 6 pm - 8 pm",
    buildingLocation: "",
    address: "32685 Medicine Bull Hwy",
    city: "Lower Brule",
    state: "SD",
    zip: "57548",
    phone: "605-295-4741",
    url: "",
    notes: "There is a short application, but no one is turned away if there is need. They are able to take perishables, frozen and shelf stable products. Diapers and wipes are distributed as available. Formula was tried at one point, but shelf dates expired before they could distribute. They are willing to try formula again if there is a need. All donations of any kind are taken and appreciated, and volunteers are welcome.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Mitchell Salvation Army",
    distributionSchedule: "Monday 11am-3pm or 5pm-6pm (by appointment only); Tuesday-Thursday 11am-3pm; Lunch: Served Monday-Friday 11:30am-12:30pm",
    buildingLocation: "",
    address: "724 N Sanborn",
    city: "Mitchell",
    state: "SD",
    zip: "57301",
    phone: "605-996-3964",
    url: "",
    notes: "Short application/income guidelines. Will need to have a ID as they take a copy of it at time of services. They do assist with Rent/utilities however that is on hold till January due to lack of funding. Tierra stated that the assist people from all over (white lake to trip, salem to letcher/howard) they are open monday through friday for the food shelve. on monday they take appointments for evening pick up. They have Companion kitchen that serves lunch daily from 11:30-12:30 can get the meal togo as well. Due to limited supplies the food shelf only allows you to get 3-4 bags of food at one time. They are very much in need of all food donations and have a cooler/freezer available. They are currently doing a cozy coat drive where you can come in the the entrance and grab any coat that fits for you to take home. Would love formula donations and would love volunteers",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "North Turner County (Parker) Food Pantry",
    distributionSchedule: "Last Wednesday night of each month from 5:00-7:00 pm and can be opened in case of emergency.",
    buildingLocation: "Boofy Quimby Memorial Center",
    address: "400 S Main Ave (Inquire at Turner Town Office)",
    city: "Parker",
    state: "SD",
    zip: "57053",
    phone: "605-297-3112",
    url: "https://www.northturnerunionpresbyterianchurch.com/outreach-activities",
    notes: "Use of the food pantry is limited to those who financially qualify under terms set by the town.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Mitchell Food Pantry",
    distributionSchedule: "Monday & Friday 12 pm - 3 pm: Tuesday & Thursday 5:00 pm - 7:00 pm; Wednesday 9:00 am - 12:00 pm",
    buildingLocation: "",
    address: "812 N Rowley Street, Suite C",
    city: "Mitchell",
    state: "SD",
    zip: "57301",
    phone: "605-990-3663",
    url: "mitchellfoodpantry@gmail.com",
    notes: "Coverage of the Mitchell area. Available to those who self-declare a gross household income of 185% of poverty level. Photo Id is required. Participants shop once a month. Pantry has the ability to take donations of frozen, fresh and shelf stable products. All donations are accepted, although cash donations allow them to purchase food at greatly discounted rates from Feeding South Dakota. Formula is not available due to lack of demand. Volunteers are not needed at this time.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Scotland Food Pantry",
    distributionSchedule: "Tuesday, 4:30 PM-6:00 PM",
    buildingLocation: "",
    address: "441 Main St",
    city: "Scotland",
    state: "SD",
    zip: "57059",
    phone: "605-201-3041",
    url: "",
    notes: "Covers Cities of Scotland, Lesterville, Olivet & Kaylor. Food Pantry & Meals on Wheels Coordination. Requirements: Must worship or go to school in Scotland School District; No documents required; Walk-in.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Vermillion Community Food Pantry",
    distributionSchedule: "Monday - 10:00 AM-12:00 PM; Tuesday & Thursday - 5:00 PM-7:00 PM; Wednesday & Friday - 2:00 PM-4:30 PM.",
    buildingLocation: "Community Connection Center",
    address: "9 Court Street",
    city: "Vermillion",
    state: "SD",
    zip: "57069",
    phone: "605-658-0118 Pantry option",
    url: "https://FeedingVermillion.org/Food-Pantry",
    notes: "Site also provides a free meal every Monday 5:00 PM-6:15 PM; food assistance to Clay County residence; Shop once a month plus 2 time is for free items; Provides Thanksgiving meal at Welcome Table.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Charlie's Cupboard Program at USD",
    distributionSchedule: "Monday 2:30 pm-6:00 pm & Thursday 4:00 pm-6:00 pm",
    buildingLocation: "Campus at USD",
    address: "414 E Clark Street Rm 114",
    city: "Vermillion",
    state: "SD",
    zip: "57069",
    phone: "605-658-3555",
    url: "https://www.CharliesCupboard@usd.edu",
    notes: "Open to USD students. Providing free items to USD students, including non-perishable groceries, personal hygiene products, school supplies; and referrals to community resources. Must have USD Student ID#/card.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Wakonda - Feeding South Dakota",
    distributionSchedule: "Tuesday 8:00 am - Bread only",
    buildingLocation: "",
    address: "205 Iowa St",
    city: "Wakonda",
    state: "SD",
    zip: "57073",
    phone: "605-661-3475",
    url: "",
    notes: "No other services.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Winner Thrift Store & Food Pantry",
    distributionSchedule: "Monday, Wednesday, Thursday and Friday 11:00 am- 4:30 pm.",
    buildingLocation: "",
    address: "222 South Main St",
    city: "Winner",
    state: "SD",
    zip: "57580",
    phone: "605-842-1525",
    url: "https://www.wma-winnerareachurches.com/projecto-1",
    notes: "Application process, photo id and two current proof-of-residency plus family household for Tripp County, can receive food once per month, applicant must be head of household and only this applicant is eligible to pick up food; income based.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Yankton Contact Center",
    distributionSchedule: "Office Hours: Monday-Friday 9am to 5:00 pm; Food Pantry: Tuesdays, Thursdays and Fridays, 9:00 AM-4:30 PM",
    buildingLocation: "",
    address: "718 Walnut Street, Ste A",
    city: "Yankton",
    state: "SD",
    zip: "57078",
    phone: "605-665-4400",
    url: "https://www.yanktoncontactcenter.org",
    notes: "No meal service; Food pantry; Payee Services; Rental Assistance; Utility Assistance; Information & Referral Financial Assistance; Backpack Project; Holiday Food Baskets. Serving all within 60 miles of Yankton.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Yankton Community Food Distribution - Feeding South Dakota",
    distributionSchedule: "Tuesday 9 AM-9:30 AM",
    buildingLocation: "",
    address: "709 Whiting Drive",
    city: "Yankton",
    state: "SD",
    zip: "57078",
    phone: "605-665-1518",
    url: "https://www.feedingsouthdakota.org",
    notes: "Community food distribution held on Tuesday mornings at the Kiwanis 4-H Ice Center; Groceries are available and varies from week to week; Open to all; no documents required; must call ahead and give name and number to register and to ensure food is available.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Yankton Food for Thought (non-profit)",
    distributionSchedule: "School Food Pantry Hrs: 4:30 pm-6:00 pm 1st Tuesday of each month.",
    buildingLocation: "Next to Calvary Baptist Church",
    address: "2407 Broadway",
    city: "Yankton",
    state: "SD",
    zip: "57078",
    phone: "605-653-0717",
    url: "https://www.yanktonfft.org",
    notes: "Provides food to those who are food insecure in the Yankton School District through The Sack Pack & School Food Pantry programs. Open to any families that are food insecure with children attending school in the Yankton School District. No documents required. Registration upon arrival for statistics and to determine child eligibility. Email: YanktonFFT@gmail.com",
  },
  {
    region: "South Central",
    programType: "Mobile Food Sites",
    programName: "Clear Lake Feeding SD Mobile",
    distributionSchedule: "Nov 13 9:00am-10:00am CT, Dec 11 9:00-10:00am CT",
    buildingLocation: "St Paul's Lutheran Church",
    address: "711 Sixth Ave S",
    city: "Clear Lake",
    state: "SD",
    zip: "57226",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Mobile Food Sites",
    programName: "Eagle Butte Feeding SD Mobile",
    distributionSchedule: "Nov 10 10:00am-12:00pm MT, Dec 8 10:00am-12:00pm MT",
    buildingLocation: "Eagle Butte Food Pantry",
    address: "521 Lincoln St",
    city: "Eagle Butte",
    state: "SD",
    zip: "57625",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Mobile Food Sites",
    programName: "Martin Feeding SD Mobile",
    distributionSchedule: "Nov 19 11:00am-12:00pm MT, Dec 17 11:00am-12:00pm MT",
    buildingLocation: "Bennett County Grade School Activity Center 'AC'",
    address: "400 Bennett Avenue",
    city: "Martin",
    state: "SD",
    zip: "57551",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Mobile Food Sites",
    programName: "Murdo Feeding SD Mobile",
    distributionSchedule: "Nov 26 2:00-3:00pm CT, Dec 30 2:00-3:00pm CT",
    buildingLocation: "Murdo Football Field",
    address: "404 S Jackson Ave",
    city: "Murdo",
    state: "SD",
    zip: "57559",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Mobile Food Sites",
    programName: "Parmelee Feeding SD Mobile",
    distributionSchedule: "Nov 20 11:00am-1:00pm CT, Dec 29 11:00am-1:00pm CT",
    buildingLocation: "St Agnes Church Hall",
    address: "1st Street",
    city: "Parmelee",
    state: "SD",
    zip: "57566",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Mobile Food Sites",
    programName: "Red Shirt Feeding SD Mobile",
    distributionSchedule: "Nov 25 12:30pm-1:30pm MT, Dec 15 12:30pm-1:30pm MT",
    buildingLocation: "Red Shirt School",
    address: "38 Tatanka Numpa Rd",
    city: "Red Shirt",
    state: "SD",
    zip: "57744",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Mobile Food Sites",
    programName: "Rapid City Feeding SD Mobile",
    distributionSchedule: "See distribution schedule online",
    buildingLocation: "",
    address: "1111 Creek Dr",
    city: "Rapid City",
    state: "SD",
    zip: "57703",
    phone: "605-335-0364",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Redfield Feeding SD Mobile",
    distributionSchedule: "Nov 6 11:00am-1:00pm CT, Dec 4 11:00am-1:00pm CT",
    buildingLocation: "National Guard Armory",
    address: "309 W 3rd St",
    city: "Redfield",
    state: "SD",
    zip: "57469",
    phone: "",
    url: "https://www.feedingsouthdakota.org/mobile",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Mobile Food Sites",
    programName: "Rosebud Feeding SD Mobile",
    distributionSchedule: "Nov 26 11:00am-1:00pm CT, Dec 30 11:00am-1:00pm CT",
    buildingLocation: "Rosebud Community Building",
    address: "500 W Frontage Rd",
    city: "Rosebud",
    state: "SD",
    zip: "57570",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Mobile Food Sites",
    programName: "Saint Francis Mission Feeding SD Mobile",
    distributionSchedule: "Nov 13 11:00am-1:00pm CT, Dec 11 11:00am-1:00pm CT",
    buildingLocation: "Saint Francis Mission, Digmann Hall",
    address: "350 S Oak St",
    city: "Saint Francis",
    state: "SD",
    zip: "57572",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "Southeast",
    programType: "Mobile Food Sites",
    programName: "Sioux Falls Feeding SD Mobile",
    distributionSchedule: "See distribution schedule online",
    buildingLocation: "",
    address: "4701 N Westport Ave",
    city: "Sioux Falls",
    state: "SD",
    zip: "57107",
    phone: "605-335-0364",
    url: "https://www.feedingsouthdakota.org/mobile?location=Sioux-Falls,-SD&radius=50",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Tolstoy Feeding SD Mobile",
    distributionSchedule: "Nov 10 11:30am-12:30pm, Dec 8 11:30am-12:30pm",
    buildingLocation: "Tolstoy Wesleyan Church",
    address: "305 Dufloth St",
    city: "Tolstoy",
    state: "SD",
    zip: "57475",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Mobile Food Sites",
    programName: "White River Feeding SD Mobile",
    distributionSchedule: "Nov 13 10:00am-12:00pm CT, Dec 11 10:00am-12:00pm CT",
    buildingLocation: "White River City Park",
    address: "Parkway St",
    city: "White River",
    state: "SD",
    zip: "57579",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "Southeast",
    programType: "Mobile Food Sites",
    programName: "Faith Temple Food Giveaway",
    distributionSchedule: "Cars can start lining up: 2:00pm (CT), Friday Food Giveaway: 4:00pm - 6:00pm (CT), Friday",
    buildingLocation: "Nordstrom-Johnson Building Sioux Empire Fairgrounds",
    address: "100 N Louise Avenue",
    city: "Sioux Falls",
    state: "SD",
    zip: "57107",
    phone: "605-332-2303",
    url: "https://www.faithtemplefood.com/",
    notes: "Text \"FOOD\" to 605-605-1225 for special food giveaways",
  },
  {
    region: "Southeast",
    programType: "Mobile Food Sites",
    programName: "Charis Ministry Partners Food to You Distribution",
    distributionSchedule: "Distribution time: 6:00pm - 7:00pm (CT), Thursday Doors open at 6:00pm, people who are in the line at 7:00pm will be served.",
    buildingLocation: "",
    address: "1300 E 10th Street",
    city: "Sioux Falls",
    state: "SD",
    zip: "57103",
    phone: "605-271-2163",
    url: "https://www.charissf.org/calendar",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Pierre Feeding SD Mobile",
    distributionSchedule: "See distribution schedule for dates online, times 11:00am - 1:00pm",
    buildingLocation: "Oahe Complex",
    address: "901 S. Buchanan Ave.",
    city: "Pierre",
    state: "SD",
    zip: "57501",
    phone: "605-494-3663",
    url: "",
    notes: "11:00am - 1:00pm",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Blunt Feeding SD Mobile",
    distributionSchedule: "9:00am - 10:00am",
    buildingLocation: "Oahe Electric",
    address: "102 S. Canfort St.",
    city: "Blunt",
    state: "SD",
    zip: "57522",
    phone: "",
    url: "",
    notes: "9:00am - 10:00am",
  },
  {
    region: "North Central",
    programType: "Mobile Food Sites",
    programName: "Onida Feeding SD Mobile",
    distributionSchedule: "3:00pm - 4:00pm",
    buildingLocation: "1st Presbyterian Church",
    address: "307 S. Main St.",
    city: "Onida",
    state: "SD",
    zip: "57564",
    phone: "",
    url: "",
    notes: "3:00pm - 4:00pm",
  },
  {
    region: "Northeast",
    programType: "Mobile Food Sites",
    programName: "Kingsbury County Food Pantry",
    distributionSchedule: "12-1pm on the 4th Wednesday of the month",
    buildingLocation: "Wilder Lane next to Washington City Park",
    address: "",
    city: "",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "They stress they do not want anyone to get out of their vehicle and will direct people.",
  },
  {
    region: "South Central",
    programType: "Mobile Food Sites",
    programName: "Rosebud Food Pantry - Mission",
    distributionSchedule: "Food pantry open 24/7; senior box pick-up Tues and Thurs 1-4 pm",
    buildingLocation: "Antelope Community Center",
    address: "2012 E Two Arrows Ave",
    city: "Mission",
    state: "SD",
    zip: "57555",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "West",
    programType: "Mobile Food Sites",
    programName: "Pine Ridge Feeding SD Mobile",
    distributionSchedule: "See distribution schedule online",
    buildingLocation: "Batesland Elementary School",
    address: "206 School Street",
    city: "Batesland",
    state: "SD",
    zip: "57716",
    phone: "",
    url: "https://www.feedingsouthdakota.org/programs/mobile-food-distribution",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Non-Food Pantries",
    programName: "Mitchell Helping Hand Pantry",
    distributionSchedule: "Take non-food items like personal hygiene, diapers, wipes",
    buildingLocation: "",
    address: "301 E 4th Ave",
    city: "Mitchell",
    state: "SD",
    zip: "57301",
    phone: "605-996-5104",
    url: "https://www.helpinghandpantryofmitchell.org/",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Non-Food Pantries",
    programName: "St Vincent de Paul",
    distributionSchedule: "Assistance with rent, utilities, clothing, furniture, household items or transportation Assistance provided a case by case basis following an in-home visit.",
    buildingLocation: "",
    address: "No physical address",
    city: "Yankton",
    state: "SD",
    zip: "57078",
    phone: "605-760-4927",
    url: "",
    notes: "By appointment only. Open to all. ID required.",
  },
  {
    region: "South Central",
    programType: "Non-Food Pantries",
    programName: "United Way of Greater Yankton Clothing Closet",
    distributionSchedule: "Offers community members who are struggling with the opportunity to receive free, quality clothing",
    buildingLocation: "",
    address: "920 Broadway Ave, Ste1",
    city: "Yankton",
    state: "SD",
    zip: "57078",
    phone: "605-665-6766",
    url: "",
    notes: "Open to all. Appointment required. Initial intake required.",
  },
  {
    region: "South Central",
    programType: "Non-Food Pantries",
    programName: "Diaper Bank Program at Evan Project Diaper Bank",
    distributionSchedule: "Provides diapers and wipes for Vermillion families in need.",
    buildingLocation: "",
    address: "9 Court Street",
    city: "Vermillion",
    state: "SD",
    zip: "57069",
    phone: "605-658-0118",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Non-Food Pantries",
    programName: "Meals on Wheels RC Sites - Senior Meals",
    distributionSchedule: "www.mealsprogram.com",
    buildingLocation: "",
    address: "",
    city: "Rapid City",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Non-Food Pantries",
    programName: "Partnership with Native Americans - Volunteer Incentive",
    distributionSchedule: "Volunteer in warehouse in exchange for goods, food boxes & supplies",
    buildingLocation: "",
    address: "2401 Eglin St",
    city: "Rapid City",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Non-Food Pantries",
    programName: "Belle Fourche Compassion Cupboard",
    distributionSchedule: "Emergency food only - Tuesdays 9-12pm and Thursdays 2-6pm.",
    buildingLocation: "",
    address: "522 5th Ave",
    city: "Belle Fourche",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Non-Food Pantries",
    programName: "Spearfish Community Action Program",
    distributionSchedule: "1st 2 Saturdays of every month, 9:30am- 1pm.",
    buildingLocation: "",
    address: "236 W Jackson Room 2",
    city: "Spearfish",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Non-Food Pantries",
    programName: "Sturgis Community Action Program",
    distributionSchedule: "M-F 8-5pm",
    buildingLocation: "",
    address: "1220 Cedar St. #113",
    city: "Sturgis",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Non-Food Pantries",
    programName: "Nisland Community Action Program NVN Cat Center",
    distributionSchedule: "Tuesdays 9AM",
    buildingLocation: "",
    address: "",
    city: "",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Non-Food Pantries",
    programName: "Fall River Thrift Store",
    distributionSchedule: "Wed, Fri, Sat 11-4pm.",
    buildingLocation: "",
    address: "",
    city: "",
    state: "SD",
    zip: "",
    phone: "605-745-3400",
    url: "",
    notes: "diapers and basic non food household items.",
  },
  {
    region: "Southeast",
    programType: "Non-Food Pantries",
    programName: "Diaper Program at Society of St Vincent de Paul",
    distributionSchedule: "The first three Wednesdays and Saturdays of the month from 9 AM to 11 AM.",
    buildingLocation: "",
    address: "431 N Cliff Avenue",
    city: "Sioux Falls",
    state: "SD",
    zip: "57103",
    phone: "",
    url: "https://svdpsd.com/holy-innocents-ministry",
    notes: "Holy Innocents Ministry offers diapers, wipes, and formula vouchers to qualified families at no charge. Program may be utilized once every 60 days.",
  },
  {
    region: "Southeast",
    programType: "Non-Food Pantries",
    programName: "Diaper Program at Society of St Vincent de Paul - Ellis Road",
    distributionSchedule: "5 PM to 7 PM on the following dates: Wednesday 11/12/2025, Tuesday 11/25/2025, Wednesday 12/10/2025, and Wednesday 12/23/2025.",
    buildingLocation: "",
    address: "3000 S Ellis Rd",
    city: "Sioux Falls",
    state: "SD",
    zip: "",
    phone: "",
    url: "https://svdpsd.com/holy-innocents-ministry",
    notes: "Holy Innocents Ministry offers diapers, wipes, and formula vouchers to qualified families at no charge. Program may be utilized once every 60 days.",
  },
  {
    region: "Southeast",
    programType: "Non-Food Pantries",
    programName: "Caminando Juntos helping the Latino Community",
    distributionSchedule: "Monday through Thursday 9 am to 5pm and Friday 9 am to 4 pm",
    buildingLocation: "",
    address: "311 East 14th Street",
    city: "Sioux Falls",
    state: "SD",
    zip: "57104",
    phone: "605-274-3735",
    url: "",
    notes: "$25.00 Grocery Voucher for food and formula",
  },
  {
    region: "North Central",
    programType: "Non-Food Pantries",
    programName: "Birthright",
    distributionSchedule: "Mon., Tues., Thurs - 2:00pm-5:00pm",
    buildingLocation: "",
    address: "314 S. Henry",
    city: "Pierre",
    state: "SD",
    zip: "57501",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "Southeast Pierre Mission United Methodist Church",
    distributionSchedule: "Community supper, every Thursday, 5:00pm-6:30pm",
    buildingLocation: "",
    address: "2315 E. Park St.",
    city: "Pierre",
    state: "SD",
    zip: "57501",
    phone: "605-224-7244",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "Community Supper by Ft. Pierre Congregation Church",
    distributionSchedule: "Community supper, every Wednesday 5:30pm-6:30pm",
    buildingLocation: "",
    address: "114 W. Main",
    city: "Ft. Pierre",
    state: "SD",
    zip: "57532",
    phone: "605-220-0712",
    url: "",
    notes: "Does post on Facebook what they are having.",
  },
  {
    region: "North Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "Good Shepherd Community Church",
    distributionSchedule: "Community meal served on the 2nd Monday of the month from 4:00pm to 6:00pm",
    buildingLocation: "",
    address: "1429 N Dakota St",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "605-229-0846",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "Bethleham Lutheran Church",
    distributionSchedule: "Community meal Wednesday 5:00pm to 6:15pm",
    buildingLocation: "",
    address: "1620 Milwaukee Ave NE",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "605-225-9740",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "New Life Fellowship Church",
    distributionSchedule: "Community meal Wednesday 5:10pm to 6:00pm",
    buildingLocation: "",
    address: "619 8th Ave NW",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "605-262-2002",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "Zion Lutheran Church",
    distributionSchedule: "Community meal 4th Monday of the month 5:30pm to 7:00pm",
    buildingLocation: "",
    address: "1732 S Main St",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "605-225-6755",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "Pierre/Ft. Pierre, Meals on Wheels for Seniors",
    distributionSchedule: "Volunteer's deliver meal's to Senior's every Tuesday",
    buildingLocation: "",
    address: "West 1st St",
    city: "Ft. Pierre",
    state: "SD",
    zip: "57532",
    phone: "605-223-2701",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "Pierre Senior Center",
    distributionSchedule: "Senior Center every Thursday Potluck",
    buildingLocation: "",
    address: "401 W. Pleasant",
    city: "Pierre",
    state: "SD",
    zip: "57501",
    phone: "605-224-7730",
    url: "",
    notes: "starting 50 yrs of age to apply",
  },
  {
    region: "Northeast",
    programType: "Free or Reduced-Cost Meals",
    programName: "Harvest Table - Brookings First United Methodist Church",
    distributionSchedule: "Free meal - Mondays 5:30 pm",
    buildingLocation: "",
    address: "625 5th St",
    city: "Brookings",
    state: "SD",
    zip: "57006",
    phone: "605-692-4345",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "Vermillion Food Pantry",
    distributionSchedule: "Free meal every Monday 5:00 PM-6:15 PM",
    buildingLocation: "",
    address: "9 Court Street",
    city: "Vermillion",
    state: "SD",
    zip: "57069",
    phone: "605-658-0118",
    url: "https://www.feedingvermillion.org/food-pantry",
    notes: "https://www.feedingvermillion.org/welcome-table",
  },
  {
    region: "South Central",
    programType: "Free or Reduced-Cost Meals",
    programName: "The Center",
    distributionSchedule: "Hours: 8am-4pm Monday thru Thursday. Plus evening events. $4.25 donation for 60 & older, $6.50 for under 60 per meal.",
    buildingLocation: "",
    address: "900 Whiting Drive",
    city: "Yankton",
    state: "SD",
    zip: "57078",
    phone: "605-665-1055",
    url: "https://thecenteryankton.net",
    notes: "Contact the Center for an intake form/application. Other services: Meals on Wheels, Shine Assistance, Tax Filing, Pet Program (pet food)",
  },
  {
    region: "West",
    programType: "Free or Reduced-Cost Meals",
    programName: "Fork Real Cafe",
    distributionSchedule: "Non Profit - Pay what you can cafe M-F 7:30-1:30pm",
    buildingLocation: "",
    address: "507 Main St.",
    city: "Rapid City",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "Community can donate meals to those who need - pay as you can. Those in need can always stop by for some food. \"Pay it Forward\"",
  },
  {
    region: "West",
    programType: "Free or Reduced-Cost Meals",
    programName: "United Churches of Hot Springs",
    distributionSchedule: "4:30-6pm Thursdays (no holidays), Mid-Oct - Mid April only.",
    buildingLocation: "",
    address: "342 N Garden St.",
    city: "Hot Springs",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "Eligible for all members of the Fall River Community - Community Spaghetti Supper.",
  },
  {
    region: "West",
    programType: "Free or Reduced-Cost Meals",
    programName: "Canyon Lake Activity Center",
    distributionSchedule: "Nutritious freshly made meal for a small fee, 11-12:30 M-F",
    buildingLocation: "",
    address: "2900 Canyon Lake Drive",
    city: "Rapid City",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "Southeast",
    programType: "Free or Reduced-Cost Meals",
    programName: "Sallie's Table Salvation Army",
    distributionSchedule: "Sallie's Table Weekend Meals: 4:45pm - 5:45pm (CT), Saturday and Sunday Sunday Morning Breakfast: 8:45am - 9:30am (CT)",
    buildingLocation: "",
    address: "800 N Cliff Ave",
    city: "Sioux Falls",
    state: "SD",
    zip: "57104",
    phone: "605-332-2331",
    url: "https://centralusa.salvationarmy.org/siouxfalls/cure-hunger/",
    notes: "",
  },
  {
    region: "Southeast",
    programType: "Free or Reduced-Cost Meals",
    programName: "The Banquet-Downtown",
    distributionSchedule: "Breakfast: 7:00am - 8:00am (CT), Monday - Friday Supper: 6:00pm - 7:30pm (CT), Monday - Friday Lunch: 11:30am - 12:30pm (CT), Saturday Office Hours: 9:30am - 4:30pm (CT), Monday - Friday",
    buildingLocation: "",
    address: "900 E 8th Street",
    city: "Sioux Falls",
    state: "SD",
    zip: "57103",
    phone: "605-335-7066",
    url: "https://thebanquetsf.org/",
    notes: "A feeding ministry that serves hot meals to anyone seeking nourishment.",
  },
  {
    region: "Southeast",
    programType: "Free or Reduced-Cost Meals",
    programName: "The Banquet-West",
    distributionSchedule: "6:00pm - 7:30pm (CT), Monday - Friday",
    buildingLocation: "",
    address: "710 N Marion Road",
    city: "Sioux Falls",
    state: "SD",
    zip: "57107",
    phone: "605-335-7066",
    url: "https://thebanquetsf.org/",
    notes: "A feeding ministry that serves hot meals to anyone seeking nourishment.",
  },
  {
    region: "Southeast",
    programType: "Free or Reduced-Cost Meals",
    programName: "Daytime Program Bishop Dudley Hospitality House",
    distributionSchedule: "Monday - Sunday Lunch: 11:30am (CT), Monday - Friday (Must be present at 11:30am to receive the meal) 3:30pm (CT)",
    buildingLocation: "",
    address: "101 N Indiana Avenue",
    city: "Sioux Falls",
    state: "SD",
    zip: "57103",
    phone: "605-809-8424",
    url: "https://www.bdhh.org/",
    notes: "Lunch meal served each day",
  },
  {
    region: "Southeast",
    programType: "Free or Reduced-Cost Meals",
    programName: "Meal Service Program Union Gospel",
    distributionSchedule: "Breakfast: 7:00am - 7:30am Lunch: 12:00noon - 12:30pm Dinner: 6:00pm - 6:30pm, with Chapel at 7:00pm",
    buildingLocation: "",
    address: "220 N Weber Avenue",
    city: "Sioux Falls",
    state: "SD",
    zip: "57103",
    phone: "605-334-6732",
    url: "",
    notes: "Meal service is open to the general public daily:",
  },
  {
    region: "Northeast",
    programType: "Free or Reduced-Cost Meals",
    programName: "Free Community Meal",
    distributionSchedule: "meal held on the 1st Tuesday of every month",
    buildingLocation: "De Smet United Methodist Church",
    address: "301 3rd St SW",
    city: "De Smet",
    state: "SD",
    zip: "57231",
    phone: "",
    url: "",
    notes: "call 605-854-3149 for more information",
  },
  {
    region: "Southeast",
    programType: "Food Pantries",
    programName: "Harrisburg Area Food Pantry",
    distributionSchedule: "Tuesday 4:00-7:00 pm or by appointment",
    buildingLocation: "",
    address: "203 Prairie St",
    city: "Harrisburg",
    state: "SD",
    zip: "57032",
    phone: "605-929-0599",
    url: "",
    notes: "",
  },
  {
    region: "Southeast",
    programType: "Food Pantries",
    programName: "Lennox Food Pantry",
    distributionSchedule: "September-May. Contact School counselor for info.",
    buildingLocation: "",
    address: "205 W 5th Ave",
    city: "Lennox",
    state: "SD",
    zip: "57039",
    phone: "605-647-2203",
    url: "",
    notes: "",
  },
  {
    region: "Southeast",
    programType: "Food Pantries",
    programName: "Lennox Ebenezer Presbyterian Church Food Pantry",
    distributionSchedule: "Wed 3:30-4:30 pm; Sat 9:00-10:00 am",
    buildingLocation: "",
    address: "305 W. 1st Ave",
    city: "Lennox",
    state: "SD",
    zip: "57039",
    phone: "605-647-2659",
    url: "",
    notes: "",
  },
  {
    region: "Southeast",
    programType: "Food Pantries",
    programName: "Union County Food Pantry",
    distributionSchedule: "Monday, Wednesday, Friday 2:30 pm – 4:30 pm",
    buildingLocation: "City Hall Building",
    address: "504 River Dr",
    city: "North Sioux City",
    state: "SD",
    zip: "57049",
    phone: "605-658-0118",
    url: "https://northsiouxcity-sd.gov/union-county-food-pantry/",
    notes: "Customers will be required to complete a short application to determine eligibility one time per year for reporting purposes.",
  },
  {
    region: "Southeast",
    programType: "Food Pantries",
    programName: "Sioux Falls Salvation Army",
    distributionSchedule: "9:30 am - 11:30 am (CT), Monday - Friday 1:00 pm - 3:30 pm (CT), Monday - Friday Closed on the 2nd Thursday of every month.",
    buildingLocation: "",
    address: "900 N Cliff Ave",
    city: "Sioux Falls",
    state: "SD",
    zip: "57103",
    phone: "605-332-2331",
    url: "https://www.salvationarmyusa.org/sd/sioux-falls/n-cliff-ave-corps/",
    notes: "Can goods, frozen meat, if available, will give out rice, bread, cereals, hygiene items, and diapers",
  },
  {
    region: "Southeast",
    programType: "Food Pantries",
    programName: "Messiah New Hope Lutheran Church",
    distributionSchedule: "10:00am - 12:00pm (CT), Mondays weekly 6:00pm - 7:00pm (CT), 4th Wednesday of every month",
    buildingLocation: "",
    address: "5001 E Madison Street",
    city: "Sioux Falls",
    state: "SD",
    zip: "57110",
    phone: "605-333-0971",
    url: "https://www.messiahnewhope.com/",
    notes: "",
  },
  {
    region: "Southeast",
    programType: "Food Pantries",
    programName: "St. Katharine Drexel Catholic Church",
    distributionSchedule: "9:00am - 12:00noon (CT), Monday 9:00am - 4:00pm (CT), Tuesday - Thursday 9:00am - 12:00noon (CT), Friday Hours subject to change for holidays and weather.",
    buildingLocation: "",
    address: "1800 S Katie Avenue Suite 1",
    city: "Sioux Falls",
    state: "SD",
    zip: "57106",
    phone: "605-275-6870",
    url: "",
    notes: "",
  },
  {
    region: "Southeast",
    programType: "Food Pantries",
    programName: "Union Gospel Mission Food Box Program",
    distributionSchedule: "1:00pm - 4:00pm (CT), Tuesday and Thursday",
    buildingLocation: "",
    address: "220 N Weber Avenue",
    city: "Sioux Falls",
    state: "SD",
    zip: "57103",
    phone: "605-334-6732",
    url: "https://ugmsiouxfalls.com/services/",
    notes: "Offering a food box program open to all. Please note - individuals must bring their own box or bag to put food in.",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Custer Storehouse Food Pantry",
    distributionSchedule: "Must reside in Custer County. Open 1st 3 Wed and Sat of each month 10AM - 1PM. Max of 2 visits/month.",
    buildingLocation: "",
    address: "66 Centennial Dr",
    city: "Custer",
    state: "SD",
    zip: "57730",
    phone: "605-673-3565",
    url: "",
    notes: "Takes donations, Food items are 3 items per person according to website. Has Food, clothing and household essentials. There is also a food pantry at the high school for students/families at the front office.",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Conscious Alliance Food Sovereignty & Youth Empowerment Center",
    distributionSchedule: "Wed 10:00 am until 50 families are served",
    buildingLocation: "",
    address: "Lakeside Rd off of BIA 35",
    city: "Oglala",
    state: "SD",
    zip: "57764",
    phone: "605-441-0605",
    url: "https://consciousalliance.org/",
    notes: "Mostly dried goods and non perishables. Opens at 10 but only serves the first 50 families each day.",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Country Cupboard Food Pantry",
    distributionSchedule: "September-May: 1st 2nd 3rd Wednesday of the month 1-4pm. 2nd and 3rd Saturday of the month. May-August: 3rd Wednesday of the month 9-11am and 5-7pm; 3rd Saturday of the month 9-11am.",
    buildingLocation: "",
    address: "505 Glenn St",
    city: "Wall",
    state: "SD",
    zip: "57790",
    phone: "605-279-1045",
    url: "",
    notes: "Eligible for anyone in Wall or Phillip area",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Rapid City Church Response",
    distributionSchedule: "Mon-Fri 9-12pm, 1-4 pm; emergency food assistance",
    buildingLocation: "",
    address: "30 Main St",
    city: "Rapid City",
    state: "SD",
    zip: "57701",
    phone: "605-342-5360",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Rapid City Lambchop Ministries",
    distributionSchedule: "by appointment only",
    buildingLocation: "",
    address: "4813 S Canyon Rd",
    city: "Rapid City",
    state: "SD",
    zip: "57701",
    phone: "605-343-1051",
    url: "",
    notes: "By appointment only.",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Mother Butler Food Pantry",
    distributionSchedule: "605-343-2165 - call for hours and documents required",
    buildingLocation: "",
    address: "231 Knollwood Dr",
    city: "Rapid City",
    state: "SD",
    zip: "57701",
    phone: "605-343-2165",
    url: "",
    notes: "ID required - no formula.",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Rapid City Salvation Army",
    distributionSchedule: "Contact for specific details and utility assistance (appt. only)",
    buildingLocation: "",
    address: "405 N Cherry Ave",
    city: "Rapid City",
    state: "SD",
    zip: "57701",
    phone: "",
    url: "",
    notes: "Food pantry limited to only those in need and what is available - not always available. Takes Donations",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Food Pantry - Hot Springs",
    distributionSchedule: "Tues Wed Thurs 10am - 12pm; Tues- Thurs 1-3pm",
    buildingLocation: "",
    address: "108 North Chicago St",
    city: "Hot Springs",
    state: "SD",
    zip: "57747",
    phone: "605-745-4034",
    url: "",
    notes: "Fall River County and Buffalo Gap are eligible. 1x a month preferred. Has formula only when donated. Has basic household items and food items that they include every other month. Takes Donations - not expired only. Partners with Feeding SD.",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Hot Springs Ministerial Association Food Pantry",
    distributionSchedule: "10-12pm Sat & 1-3pm Tues-Thurs.",
    buildingLocation: "",
    address: "108 Chicago",
    city: "Hot Springs",
    state: "SD",
    zip: "57747",
    phone: "",
    url: "",
    notes: "ID with current address is required. Eligible for those in Fall River County.",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Adventist Food Pantry",
    distributionSchedule: "8-4pm Sun - Thurs, ID required",
    buildingLocation: "",
    address: "4703 S Canyon Road",
    city: "Rapid City",
    state: "SD",
    zip: "57701",
    phone: "605-389-6225",
    url: "",
    notes: "ID or Social Security card required. Food Pantry and some personal items depending on what has been donated.",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Edgemont Food Pantry",
    distributionSchedule: "Mondays 1-2pm, Thursdays 5:30-6:30pm",
    buildingLocation: "",
    address: "410 4th St.",
    city: "Edgemont",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Hill City Community Food Pantry",
    distributionSchedule: "9-11AM Mondays and Fridays",
    buildingLocation: "",
    address: "525 Main St",
    city: "Hill City",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Newell Ministerial Food Pantry",
    distributionSchedule: "1st & 3rd Thursdays 1-2pm",
    buildingLocation: "",
    address: "120 6th St.",
    city: "Newell",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "West",
    programType: "Food Pantries",
    programName: "Lord's Cupboard",
    distributionSchedule: "M-F 8-5pm",
    buildingLocation: "",
    address: "111 S Main St",
    city: "Lead",
    state: "SD",
    zip: "",
    phone: "",
    url: "",
    notes: "",
  },
  
];
export default SDresourceList;