const SDresourceList = [
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Aberdeen Salvation Army",
    distributionSchedule: "Contact Agency for Distribution Times",
    buildingLocation: "",
    address: "1003 6th Ave SW",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "605-225-7410",
    url: "",
    notes: "Food Pantry: week’s supply of food, can use every 90 days. Free community meal Monday to Friday 12:00pm to 1:00 pm",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Bowdle Food Pantry",
    distributionSchedule: "Monday - Thursday 10:00am to 4:00pm (closed over lunch) or by appointment (call Joell Bieber at 605-281-0828 for scheduling)",
    buildingLocation: "City office",
    address: "4093 9th Ave",
    city: "Bowdle",
    state: "SD",
    zip: "57428",
    phone: "605-281-0828",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Brown Bag Food Pantry of Faulkton",
    distributionSchedule: "4th Tues of the month 12-2 and 5:30-7; can call Karen Collins at 605-350-4227 for immediate needs",
    buildingLocation: "United Church of Faulkton (Methodist Church)",
    address: "1011 St John St",
    city: "Faulkton",
    state: "SD",
    zip: "57438",
    phone: "605-598-6580 (Church), 605-350-4227 (Karen Collins)",
    url: "https://www.facebook.com/FaulktonUMC/",
    notes: "No application process or requirements. All people are welcome. All donations are welcome, food and non-food. Can accept perishables. Each person receives one brown bag with about 17 items. Items are meant to combine to make 2-3 meals. Typically includes1 lb fresh ground beef, canned chicken and/or tuna (with hamburger/chicken/tuna helper meal boxes), 3 cans of vegetables, 3 cans of fruit, and soup. Occasstional extras: cake mix, pancake mix & syrup, honey, powdered milk, pasta sauce, noodles, potato flakes, etc. Try to offer atleast one drink, such as coffee, tea or lemonade mix. No diapers or wipes available right now, but will gladly accept as donations.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "St Thomas Food Pantry",
    distributionSchedule: "Tues, Wed, & Thurs 10am-3pm",
    buildingLocation: "St. Thomas Catholic Church",
    address: "1013 Court St",
    city: "Faulkton",
    state: "SD",
    zip: "57438",
    phone: "605-598-6590",
    url: "",
    notes: "No application process or requirements. All people are welcome. Accepting cash and non-perishable food donations. The church collects food and takes to the food pantry in Redfield. The Redfield food pantry then sends back bags of groceries that can be given out. Some non-food items available, but not consistenly.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Groton Food Pantry",
    distributionSchedule: "Contact Agency for Distribution Times",
    buildingLocation: "",
    address: "109 North 3rd Street",
    city: "Groton",
    state: "SD",
    zip: "57445",
    phone: "605-397-7097",
    url: "",
    notes: "Left a VM for a call back (ah)",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Lemmon Food Pantry",
    distributionSchedule: "Friday 7:00pm-9:00pm; Or by appointment",
    buildingLocation: "",
    address: "211 1st Avenue West",
    city: "Lemmon",
    state: "SD",
    zip: "57638",
    phone: "605-374-7617",
    url: "",
    notes: "Left a VM for a call back (ah)",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Wessington Springs Food Pantry",
    distributionSchedule: "Distributions on the Third Tuesday of the month, 10am to 11am",
    buildingLocation: "",
    address: "608 1st St NE",
    city: "Wessington Springs",
    state: "SD",
    zip: "57382",
    phone: "605-999-5883",
    url: "",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "SWO Food Pantry",
    distributionSchedule: "Monday 1:00 PM-4:00 PM, Wednesday-Friday 9 AM-12:00 PM and 1:00 PM-3:00 PM",
    buildingLocation: "",
    address: "45672 Veterans Memorial Dr",
    city: "Agency Village",
    state: "SD",
    zip: "57262",
    phone: "605-698-3643",
    url: "",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Grant County Food Pantry",
    distributionSchedule: "Hours Monday-Friday 8 am-4:30 pm  Call to schedule an appointment.",
    buildingLocation: "County Courthouse",
    address: "210 E. 5th Avenue",
    city: "Milbank",
    state: "SD",
    zip: "57252",
    phone: "605-432-6571",
    url: "",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Brookings County Food Pantry",
    distributionSchedule: "M, W, F; 1:00pm-4:30p",
    buildingLocation: "",
    address: "908 Hope Drive",
    city: "Brookings",
    state: "SD",
    zip: "57006",
    phone: "605-692-5007",
    url: "https://www.feedingbrookings.org/",
    notes: "have a picture ID and current mail with current address. Brookings County residents only.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Feeding Brookings - Ascension Lutheran Church",
    distributionSchedule: "Food distribution weekly on Thursdays - 3pm-5pm",
    buildingLocation: "",
    address: "2030 3rd St",
    city: "Brookings",
    state: "SD",
    zip: "57006",
    phone: "605-697-0477",
    url: "feedingbrookings@brookings.net",
    notes: "Show up and get in line of cars. Some paperwork and low income requirements.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Miner County (Howard) Food Pantry",
    distributionSchedule: "Tuesday and Thursday, 8:30 AM-4:00 PM",
    buildingLocation: "",
    address: "108 E Highway 34",
    city: "Howard",
    state: "SD",
    zip: "57349",
    phone: "605-772-5712",
    url: "https://www.interlakescap.com/custom/miner-county",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Sisseton Food Pantry",
    distributionSchedule: "call for distribution dates, 3:00 PM-5:00 PM",
    buildingLocation: "Family Life Church",
    address: "405 1st Ave W",
    city: "Sisseton",
    state: "SD",
    zip: "57262",
    phone: "605-698-7631",
    url: "",
    notes: "do not need to qualify",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Horizons Thrift Store (Wilmot)",
    distributionSchedule: "Wednesday-Friday, 1:00 PM-5:00 PM and Saturday 10:00 AM-2:00 PM",
    buildingLocation: "",
    address: "710 Main St",
    city: "Wilmot",
    state: "SD",
    zip: "57279",
    phone: "",
    url: "",
    notes: "***Could not verify with phone as no phone number or website. according to facebook it's a non profit thrift store.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Storehouse Program at Access Ministry",
    distributionSchedule: "Supply of food items",
    buildingLocation: "",
    address: "25 W Kemp Ave",
    city: "Watertown",
    state: "SD",
    zip: "57201",
    phone: "605-878-1478",
    url: "",
    notes: "Left a VM for a call back",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Blessing Box Program at Trinity Episcopal Church",
    distributionSchedule: "Not a food pantry, rather a cupboard to offer needed items to help people get by",
    buildingLocation: "",
    address: "612 3rd St NE",
    city: "Watertown",
    state: "SD",
    zip: "57201",
    phone: "605-868-2425",
    url: "",
    notes: "Left a VM for a call back",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Salvation Army Watertown",
    distributionSchedule: "Assists individuals and families with a food pantry and food box. Food boxes are available for pickup once a month. A community meal is served M/W/F from 11:30am-12:30pm.",
    buildingLocation: "",
    address: "621 4th St SE",
    city: "Watertown",
    state: "SD",
    zip: "57201",
    phone: "605-886-4030",
    url: "",
    notes: "You can dine-in or get a to-go box. Provide diapers, baby food, formula and soft food.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Food Distribution Program at Sisseton-Wahpeton Oyate Tribe",
    distributionSchedule: "Food distribution provides food packages to low-income families in Marshall, Day and Roberts counties, Tribal members in surrounding counties including Codington County.",
    buildingLocation: "East of the Tribal Headquarters",
    address: "",
    city: "Sisseton",
    state: "SD",
    zip: "57262",
    phone: "605-698-3762",
    url: "",
    notes: "Must qualify and bring in all required information. Call for distribution dates. Hours of distribution 9-11:30am and 1-3pm.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Hot Meal Program at Harvest Table",
    distributionSchedule: "Home cooked meal served every Monday at 5:30pm.",
    buildingLocation: "Brookings First United Methodist Church",
    address: "625 5th St",
    city: "Brookings",
    state: "SD",
    zip: "57006",
    phone: "605-692-4345",
    url: "",
    notes: "Diapers, baby wipes, household items and personal care items available. No cost",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Bethania Lutheran Food Pantry",
    distributionSchedule: "Primarily food to those in need. Some basic needs available.",
    buildingLocation: "",
    address: "9 1st St",
    city: "Rosholt",
    state: "SD",
    zip: "57260",
    phone: "605-537-4263",
    url: "",
    notes: "No qualification requirements",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Kingsbury County Food Pantry",
    distributionSchedule: "Open Tuesdays 1pm-4pm.",
    buildingLocation: "",
    address: "221 Calumet Ave SW",
    city: "DeSmet",
    state: "SD",
    zip: "57231",
    phone: "",
    url: "",
    notes: "",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "Breadbasket Food Pantry",
    distributionSchedule: "1:30-5pm Thursdays",
    buildingLocation: "",
    address: "202 E 2nd Ave",
    city: "Flandreau",
    state: "SD",
    zip: "57028",
    phone: "605-573-0935",
    url: "",
    notes: "Serves Moody County, open to all who meet income guidelines. No one in crisis will be turned away. Occasionally offers household cleaning supplies and hygiene products.",
  },
  {
    region: "Northeast",
    programType: "Food Pantries",
    programName: "24/7 Community Food Pantry",
    distributionSchedule: "24 hour food pantry",
    buildingLocation: "Entryway to City Hall",
    address: "112 N Main Ave",
    city: "Colman",
    state: "SD",
    zip: "57017",
    phone: "605-534-3611",
    url: "",
    notes: "Non-perishable food items",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Douglas County (Armour) Food Pantry",
    distributionSchedule: "Food Pantry: Tuesday 12:00pm-4:00pm",
    buildingLocation: "",
    address: "706 Braddock St",
    city: "Armour",
    state: "SD",
    zip: "57317",
    phone: "605-999-0483",
    url: "",
    notes: "Income Guidelines apply, short application process that can be completed there in person. They do have limited formula on hand due to a recent donation that came in but normally does not have it on hand. Barb stated that the clients that they are currently serving are elderly members of the community. Barb stated that she is always excepting donations and has space for both perishables and none perishables. The site is set up as a shop your own food setting, Barb stated that they do limit items to family size",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Beresford Community Food Cupboard and Services",
    distributionSchedule: "Mon-Fri 1PM-6PM and Sat 9AM-1PM",
    buildingLocation: "",
    address: "106 N 3rd St",
    city: "Beresford",
    state: "SD",
    zip: "57004",
    phone: "605-763-8888",
    url: "",
    notes: "left VM for call back (AML)",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Beresford Faith in Action",
    distributionSchedule: "Open Thursday from 1-6P and every other Saturday from 9-1P. MUST MAKE APPT.",
    buildingLocation: "",
    address: "101 S 5th St",
    city: "Beresford",
    state: "SD",
    zip: "57004",
    phone: "605-763-8019",
    url: "",
    notes: "Beresford Faith in Action serves clients in need of food; utility and rent assistance in the city of Beresford as well as those living in Union or Lincoln County. Left VM for call back(AML)",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Centerville Food Pantry",
    distributionSchedule: "Wednesday 5:30 PM-6:30 PM",
    buildingLocation: "",
    address: "548 Broadway",
    city: "Centerville",
    state: "SD",
    zip: "57014",
    phone: "605-677-9609",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Elk Point Food Pantry",
    distributionSchedule: "Tuesday and Thursday, 10:00 AM-12:00 PM and 4:00 PM-6:00 PM",
    buildingLocation: "",
    address: "107 N Douglas St",
    city: "Elk Point",
    state: "SD",
    zip: "57025",
    phone: "605-212-5403",
    url: "https://www.facebook.com/p/Elk-Point-Food-Pantry-100064583026135/",
    notes: "Income based; provides commodity foods; food pantry; charity fund available. Covers southern Union County.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Fort Thompson Food Pantry",
    distributionSchedule: "The last 3 days of the month 1:00pm-4:00pm",
    buildingLocation: "",
    address: "817 SD Hwy 47",
    city: "Fort Thompson",
    state: "SD",
    zip: "57339",
    phone: "605-245-2350",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Diamond Willow Ministries Food Pantry",
    distributionSchedule: "Provides emergency food services on the reservation",
    buildingLocation: "",
    address: "22850 North Shore Rd",
    city: "Fort Thompson",
    state: "SD",
    zip: "57339",
    phone: "605-245-2685",
    url: "https://www.d-w-m.org/iocc-programming.html",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Bethany Mennonite Church Food Pantry",
    distributionSchedule: "1st and 3rd Friday of each month, 1:00 PM-5:00 PM",
    buildingLocation: "",
    address: "509 S Juniper St",
    city: "Freeman",
    state: "SD",
    zip: "57029",
    phone: "605-925-7311",
    url: "https://www.bethanymennonite.com/foodpantry",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Irene Food Pantry",
    distributionSchedule: "Wednesday 5:30 - 6:30",
    buildingLocation: "",
    address: "110 S Till",
    city: "Irene",
    state: "SD",
    zip: "57037",
    phone: "605-660-6558",
    url: "",
    notes: "Accepting donations, fill out short application but is usually same folks. Donations: non perishable usually. Gets some form Feeding SD and they fill in as needed. She does take perishables. Not usually having formula or diapers. On occasion will have formula donations. Accepts cash or food. Call you for any donations. Asks church and bank for donations for food drive. Only open Wed but she is available to meet someone on other days and pastor may have access on other days.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Kimball Food Pantry",
    distributionSchedule: "Thursday 5:00-6:30 pm",
    buildingLocation: "",
    address: "123 S Main St",
    city: "Kimball",
    state: "SD",
    zip: "57355",
    phone: "605-450-0740",
    url: "",
    notes: "",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Lower Brule Food Pantry",
    distributionSchedule: "Sunday 1:00pm-4:00pm, Tuesdays & Thursdays 6 pm - 8 pm",
    buildingLocation: "",
    address: "32685 Medicine Bull Hwy",
    city: "Lower Brule",
    state: "SD",
    zip: "57548",
    phone: "605-295-4741",
    url: "",
    notes: "There is a short application, but no one is turned away if there is need. They are able to take perishables, frozen and shelf stable products. Diapers and wipes are distributed as available. Formula was tried at one point, but shelf dates expired before they could distribute. They are willing to try formula again if there is a need. All donations of any kind are taken and appreciated, and volunteers are welcome.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Mitchell Salvation Army",
    distributionSchedule: "Monday 11am-3pm or 5pm-6pm (by appointment only); Tuesday-Thursday 11am-3pm; Lunch: Served Monday-Friday 11:30am-12:30pm",
    buildingLocation: "",
    address: "724 N Sanborn",
    city: "Mitchell",
    state: "SD",
    zip: "57301",
    phone: "605-996-3964",
    url: "",
    notes: "Short application/income guidelines. Will need to have a ID as they take a copy of it at time of services. They do assist with Rent/utilities however that is on hold till January due to lack of funding. Tierra stated that the assist people from all over (white lake to trip, salem to letcher/howard) they are open monday through friday for the food shelve. on monday they take appointments for evening pick up. They have Companion kitchen that serves lunch daily from 11:30-12:30 can get the meal togo as well. Due to limited supplies the food shelf only allows you to get 3-4 bags of food at one time. They are very much in need of all food donations and have a cooler/freezer available. They are currently doing a cozy coat drive where you can come in the the entrance and grab any coat that fits for you to take home. Would love formula donations and would love volunteers",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "North Turner County (Parker) Food Pantry",
    distributionSchedule: "Last Wednesday night of each month from 5:00-7:00 pm and can be opened in case of emergency.",
    buildingLocation: "Boofy Quimby Memorial Center",
    address: "400 S Main Ave (Inquire at Turner Town Office)",
    city: "Parker",
    state: "SD",
    zip: "57053",
    phone: "605-297-3112",
    url: "https://www.northturnerunionpresbyterianchurch.com/outreach-activities",
    notes: "Use of the food pantry is limited to those who financially qualify under terms set by the town.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Mitchell Food Pantry",
    distributionSchedule: "Monday & Friday 12 pm - 3 pm: Tuesday & Thursday 5:00 pm - 7:00 pm; Wednesday 9:00 am - 12:00 pm",
    buildingLocation: "",
    address: "812 N Rowley Street, Suite C",
    city: "Mitchell",
    state: "SD",
    zip: "57301",
    phone: "605-990-3663",
    url: "mitchellfoodpantry@gmail.com",
    notes: "Coverage of the Mitchell area. Available to those who self-declare a gross household income of 185% of poverty level. Photo Id is required. Participants shop once a month. Pantry has the ability to take donations of frozen, fresh and shelf stable products. All donations are accepted, although cash donations allow them to purchase food at greatly discounted rates from Feeding South Dakota. Formula is not available due to lack of demand. Volunteers are not needed at this time.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Scotland Food Pantry",
    distributionSchedule: "Tuesday, 4:30 PM-6:00 PM",
    buildingLocation: "",
    address: "441 Main St",
    city: "Scotland",
    state: "SD",
    zip: "57059",
    phone: "605-201-3041",
    url: "",
    notes: "Covers Cities of Scotland, Lesterville, Olivet & Kaylor. Food Pantry & Meals on Wheels Coordination. Requirements: Must worship or go to school in Scotland School District; No documents required; Walk-in.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Vermillion Community Food Pantry",
    distributionSchedule: "Monday - 10:00 AM-12:00 PM; Tuesday & Thursday - 5:00 PM-7:00 PM; Wednesday & Friday - 2:00 PM-4:30 PM.",
    buildingLocation: "Community Connection Center",
    address: "9 Court Street",
    city: "Vermillion",
    state: "SD",
    zip: "57069",
    phone: "605-658-0118 Pantry option",
    url: "https://FeedingVermillion.org/Food-Pantry",
    notes: "Site also provides a free meal every Monday 5:00 PM-6:15 PM; food assistance to Clay County residence; Shop once a month plus 2 time is for free items; Provides Thanksgiving meal at Welcome Table.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Charlie's Cupboard Program at USD",
    distributionSchedule: "Monday 2:30 pm-6:00 pm & Thursday 4:00 pm-6:00 pm",
    buildingLocation: "Campus at USD",
    address: "414 E Clark Street Rm 114",
    city: "Vermillion",
    state: "SD",
    zip: "57069",
    phone: "605-658-3555",
    url: "https://www.CharliesCupboard@usd.edu",
    notes: "Open to USD students. Providing free items to USD students, including non-perishable groceries, personal hygiene products, school supplies; and referrals to community resources. Must have USD Student ID#/card.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Wakonda - Feeding South Dakota",
    distributionSchedule: "Tuesday 8:00 am - Bread only",
    buildingLocation: "",
    address: "205 Iowa St",
    city: "Wakonda",
    state: "SD",
    zip: "57073",
    phone: "605-661-3475",
    url: "",
    notes: "No other services.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Winner Thrift Store & Food Pantry",
    distributionSchedule: "Monday, Wednesday, Thursday and Friday 11:00 am- 4:30 pm.",
    buildingLocation: "",
    address: "222 South Main St",
    city: "Winner",
    state: "SD",
    zip: "57580",
    phone: "605-842-1525",
    url: "https://www.wma-winnerareachurches.com/projecto-1",
    notes: "Application process, photo id and two current proof-of-residency plus family household for Tripp County, can receive food once per month, applicant must be head of household and only this applicant is eligible to pick up food; income based.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Yankton Contact Center",
    distributionSchedule: "Office Hours: Monday-Friday 9am to 5:00 pm; Food Pantry: Tuesdays, Thursdays and Fridays, 9:00 AM-4:30 PM",
    buildingLocation: "",
    address: "718 Walnut Street, Ste A",
    city: "Yankton",
    state: "SD",
    zip: "57078",
    phone: "605-665-4400",
    url: "https://www.yanktoncontactcenter.org",
    notes: "No meal service; Food pantry; Payee Services; Rental Assistance; Utility Assistance; Information & Referral Financial Assistance; Backpack Project; Holiday Food Baskets. Serving all within 60 miles of Yankton.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Yankton Community Food Distribution - Feeding South Dakota",
    distributionSchedule: "Tuesday 9 AM-9:30 AM",
    buildingLocation: "",
    address: "709 Whiting Drive",
    city: "Yankton",
    state: "SD",
    zip: "57078",
    phone: "605-665-1518",
    url: "https://www.feedingsouthdakota.org",
    notes: "Community food distribution held on Tuesday mornings at the Kiwanis 4-H Ice Center; Groceries are available and varies from week to week; Open to all; no documents required; must call ahead and give name and number to register and to ensure food is available.",
  },
  {
    region: "South Central",
    programType: "Food Pantries",
    programName: "Yankton Food for Thought (non-profit)",
    distributionSchedule: "School Food Pantry Hrs: 4:30 pm-6:00 pm 1st Tuesday of each month.",
    buildingLocation: "Next to Calvary Baptist Church",
    address: "2407 Broadway",
    city: "Yankton",
    state: "SD",
    zip: "57078",
    phone: "605-653-0717",
    url: "https://www.yanktonfft.org",
    notes: "Provides food to those who are food insecure in the Yankton School District through The Sack Pack & School Food Pantry programs. Open to any families that are food insecure with children attending school in the Yankton School District. No documents required. Registration upon arrival for statistics and to determine child eligibility. Email: YanktonFFT@gmail.com",
  },
  
];
export default SDresourceList;