const SDresourceList = [
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Aberdeen Salvation Army",
    distributionSchedule: "Contact Agency for Distribution Times",
    buildingLocation: "",
    address: "1003 6th Ave SW",
    city: "Aberdeen",
    state: "SD",
    zip: "57401",
    phone: "605-225-7410",
    url: "",
    notes: "Food Pantry: week’s supply of food, can use every 90 days. Free community meal Monday to Friday 12:00pm to 1:00 pm",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Bowdle Food Pantry",
    distributionSchedule: "Monday - Thursday 10:00am to 4:00pm (closed over lunch) or by appointment (call Joell Bieber at 605-281-0828 for scheduling)",
    buildingLocation: "City office",
    address: "4093 9th Ave",
    city: "Bowdle",
    state: "SD",
    zip: "57428",
    phone: "605-281-0828",
    url: "",
    notes: "",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Brown Bag Food Pantry of Faulkton",
    distributionSchedule: "4th Tues of the month 12-2 and 5:30-7; can call Karen Collins at 605-350-4227 for immediate needs",
    buildingLocation: "United Church of Faulkton (Methodist Church)",
    address: "1011 St John St",
    city: "Faulkton",
    state: "SD",
    zip: "57438",
    phone: "605-598-6580 (Church), 605-350-4227 (Karen Collins)",
    url: "https://www.facebook.com/FaulktonUMC/",
    notes: "No application process or requirements. All people are welcome. All donations are welcome, food and non-food. Can accept perishables. Each person receives one brown bag with about 17 items. Items are meant to combine to make 2-3 meals. Typically includes1 lb fresh ground beef, canned chicken and/or tuna (with hamburger/chicken/tuna helper meal boxes), 3 cans of vegetables, 3 cans of fruit, and soup. Occasstional extras: cake mix, pancake mix & syrup, honey, powdered milk, pasta sauce, noodles, potato flakes, etc. Try to offer atleast one drink, such as coffee, tea or lemonade mix. No diapers or wipes available right now, but will gladly accept as donations.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "St Thomas Food Pantry",
    distributionSchedule: "Tues, Wed, & Thurs 10am-3pm",
    buildingLocation: "St. Thomas Catholic Church",
    address: "1013 Court St",
    city: "Faulkton",
    state: "SD",
    zip: "57438",
    phone: "605-598-6590",
    url: "",
    notes: "No application process or requirements. All people are welcome. Accepting cash and non-perishable food donations. The church collects food and takes to the food pantry in Redfield. The Redfield food pantry then sends back bags of groceries that can be given out. Some non-food items available, but not consistenly.",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Groton Food Pantry",
    distributionSchedule: "Contact Agency for Distribution Times",
    buildingLocation: "",
    address: "109 North 3rd Street",
    city: "Groton",
    state: "SD",
    zip: "57445",
    phone: "605-397-7097",
    url: "",
    notes: "Left a VM for a call back (ah)",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Lemmon Food Pantry",
    distributionSchedule: "Friday 7:00pm-9:00pm; Or by appointment",
    buildingLocation: "",
    address: "211 1st Avenue West",
    city: "Lemmon",
    state: "SD",
    zip: "57638",
    phone: "605-374-7617",
    url: "",
    notes: "Left a VM for a call back (ah)",
  },
  {
    region: "North Central",
    programType: "Food Pantries",
    programName: "Wessington Springs Food Pantry",
    distributionSchedule: "Distributions on the Third Tuesday of the month, 10am to 11am",
    buildingLocation: "",
    address: "608 1st St NE",
    city: "Wessington Springs",
    state: "SD",
    zip: "57382",
    phone: "605-999-5883",
    url: "",
    notes: "",
  },
];
module.exports = SDresourceList;